# Generated by Django 4.1.7 on 2023-03-19 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingREST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=5)),
                ('started_reading', models.DateField(blank=True, null=True)),
                ('current_page', models.CharField(blank=True, max_length=5, null=True)),
                ('finished_reading', models.DateField(blank=True, null=True)),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
