# Generated by Django 4.1.7 on 2023-03-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=5)),
                ('book_type', models.CharField(max_length=50)),
                ('started_reading', models.DateTimeField()),
                ('finished_reading', models.DateTimeField()),
                ('thoughts', models.TextField()),
                ('learnt', models.TextField()),
                ('recommended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['started_reading'],
            },
        ),
    ]
