# Generated by Django 4.1.7 on 2023-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='book_type',
            new_name='genre',
        ),
    ]
