# Generated by Django 4.1.7 on 2023-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_rename_book_type_reading_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='finished_reading',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='learnt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='started_reading',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='thoughts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
