# Generated by Django 4.1.7 on 2023-03-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_alter_reading_finished_reading_alter_reading_learnt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['title']},
        ),
    ]
