# Generated by Django 4.1.7 on 2023-03-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_alter_reading_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='at_page',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
