# Generated by Django 4.1.7 on 2023-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_reading_at_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='at_page',
            new_name='current_page',
        ),
    ]
